// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: todolist/v1/todolist.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShowKeyTodoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keywords string `protobuf:"bytes,1,opt,name=keywords,proto3" json:"keywords,omitempty"`
	Page     string `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Num      string `protobuf:"bytes,3,opt,name=num,proto3" json:"num,omitempty"`
	Token    string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ShowKeyTodoRequest) Reset() {
	*x = ShowKeyTodoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_v1_todolist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowKeyTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowKeyTodoRequest) ProtoMessage() {}

func (x *ShowKeyTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_v1_todolist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowKeyTodoRequest.ProtoReflect.Descriptor instead.
func (*ShowKeyTodoRequest) Descriptor() ([]byte, []int) {
	return file_todolist_v1_todolist_proto_rawDescGZIP(), []int{0}
}

func (x *ShowKeyTodoRequest) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *ShowKeyTodoRequest) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *ShowKeyTodoRequest) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

func (x *ShowKeyTodoRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ShowAllTodoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Page   string `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Num    string `protobuf:"bytes,3,opt,name=num,proto3" json:"num,omitempty"`
	Token  string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ShowAllTodoRequest) Reset() {
	*x = ShowAllTodoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_v1_todolist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowAllTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowAllTodoRequest) ProtoMessage() {}

func (x *ShowAllTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_v1_todolist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowAllTodoRequest.ProtoReflect.Descriptor instead.
func (*ShowAllTodoRequest) Descriptor() ([]byte, []int) {
	return file_todolist_v1_todolist_proto_rawDescGZIP(), []int{1}
}

func (x *ShowAllTodoRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ShowAllTodoRequest) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *ShowAllTodoRequest) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

func (x *ShowAllTodoRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DeleteTodoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteTodoRequest) Reset() {
	*x = DeleteTodoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_v1_todolist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoRequest) ProtoMessage() {}

func (x *DeleteTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_v1_todolist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoRequest.ProtoReflect.Descriptor instead.
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) {
	return file_todolist_v1_todolist_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteTodoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ModifyTodoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ModifyTodoRequest) Reset() {
	*x = ModifyTodoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_v1_todolist_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyTodoRequest) ProtoMessage() {}

func (x *ModifyTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_v1_todolist_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyTodoRequest.ProtoReflect.Descriptor instead.
func (*ModifyTodoRequest) Descriptor() ([]byte, []int) {
	return file_todolist_v1_todolist_proto_rawDescGZIP(), []int{3}
}

func (x *ModifyTodoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddTodoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title   string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token   string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Endtime int64  `protobuf:"varint,4,opt,name=endtime,proto3" json:"endtime,omitempty"`
}

func (x *AddTodoRequest) Reset() {
	*x = AddTodoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_v1_todolist_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTodoRequest) ProtoMessage() {}

func (x *AddTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_v1_todolist_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTodoRequest.ProtoReflect.Descriptor instead.
func (*AddTodoRequest) Descriptor() ([]byte, []int) {
	return file_todolist_v1_todolist_proto_rawDescGZIP(), []int{4}
}

func (x *AddTodoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddTodoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddTodoRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AddTodoRequest) GetEndtime() int64 {
	if x != nil {
		return x.Endtime
	}
	return 0
}

type AddTodoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AddTodoReply) Reset() {
	*x = AddTodoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_v1_todolist_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTodoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTodoReply) ProtoMessage() {}

func (x *AddTodoReply) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_v1_todolist_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTodoReply.ProtoReflect.Descriptor instead.
func (*AddTodoReply) Descriptor() ([]byte, []int) {
	return file_todolist_v1_todolist_proto_rawDescGZIP(), []int{5}
}

func (x *AddTodoReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddTodoReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DeleteTodoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DeleteTodoReply) Reset() {
	*x = DeleteTodoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_v1_todolist_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTodoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoReply) ProtoMessage() {}

func (x *DeleteTodoReply) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_v1_todolist_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoReply.ProtoReflect.Descriptor instead.
func (*DeleteTodoReply) Descriptor() ([]byte, []int) {
	return file_todolist_v1_todolist_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTodoReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteTodoReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ModifyTodoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ModifyTodoReply) Reset() {
	*x = ModifyTodoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_v1_todolist_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyTodoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyTodoReply) ProtoMessage() {}

func (x *ModifyTodoReply) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_v1_todolist_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyTodoReply.ProtoReflect.Descriptor instead.
func (*ModifyTodoReply) Descriptor() ([]byte, []int) {
	return file_todolist_v1_todolist_proto_rawDescGZIP(), []int{7}
}

func (x *ModifyTodoReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ModifyTodoReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ShowAllTodoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ShowAllTodoReply) Reset() {
	*x = ShowAllTodoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_v1_todolist_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowAllTodoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowAllTodoReply) ProtoMessage() {}

func (x *ShowAllTodoReply) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_v1_todolist_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowAllTodoReply.ProtoReflect.Descriptor instead.
func (*ShowAllTodoReply) Descriptor() ([]byte, []int) {
	return file_todolist_v1_todolist_proto_rawDescGZIP(), []int{8}
}

func (x *ShowAllTodoReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ShowAllTodoReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ShowAllTodoReply) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ShowKeyTodoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ShowKeyTodoReply) Reset() {
	*x = ShowKeyTodoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todolist_v1_todolist_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowKeyTodoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowKeyTodoReply) ProtoMessage() {}

func (x *ShowKeyTodoReply) ProtoReflect() protoreflect.Message {
	mi := &file_todolist_v1_todolist_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowKeyTodoReply.ProtoReflect.Descriptor instead.
func (*ShowKeyTodoReply) Descriptor() ([]byte, []int) {
	return file_todolist_v1_todolist_proto_rawDescGZIP(), []int{9}
}

func (x *ShowKeyTodoReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ShowKeyTodoReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ShowKeyTodoReply) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_todolist_v1_todolist_proto protoreflect.FileDescriptor

var file_todolist_v1_todolist_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x6f,
	0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x6f,
	0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x12, 0x53, 0x68, 0x6f, 0x77, 0x4b,
	0x65, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x68, 0x0a, 0x12, 0x53, 0x68, 0x6f, 0x77, 0x41, 0x6c, 0x6c,
	0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x23, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x54, 0x6f,
	0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x70, 0x0a, 0x0e, 0x41, 0x64, 0x64,
	0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x34, 0x0a, 0x0c, 0x41,
	0x64, 0x64, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0x37, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x37, 0x0a, 0x0f, 0x4d, 0x6f,
	0x64, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x4c, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x77, 0x41, 0x6c, 0x6c, 0x54, 0x6f,
	0x64, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x4c, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x77, 0x4b, 0x65, 0x79, 0x54, 0x6f, 0x64, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32,
	0xe6, 0x03, 0x0a, 0x08, 0x54, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x53, 0x0a, 0x03,
	0x41, 0x64, 0x64, 0x12, 0x1b, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x64, 0x64, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x0e, 0x22, 0x09, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x3a, 0x01,
	0x2a, 0x12, 0x60, 0x0a, 0x07, 0x53, 0x68, 0x6f, 0x77, 0x41, 0x6c, 0x6c, 0x12, 0x1f, 0x2e, 0x74,
	0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x41,
	0x6c, 0x6c, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x77,
	0x41, 0x6c, 0x6c, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x2f,
	0x61, 0x6c, 0x6c, 0x12, 0x60, 0x0a, 0x07, 0x53, 0x68, 0x6f, 0x77, 0x4b, 0x65, 0x79, 0x12, 0x1f,
	0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f,
	0x77, 0x4b, 0x65, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68,
	0x6f, 0x77, 0x4b, 0x65, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x6f, 0x64,
	0x6f, 0x2f, 0x6b, 0x65, 0x79, 0x12, 0x5e, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x1e, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x10, 0x2a, 0x0e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x6f, 0x64, 0x6f,
	0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x61, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x12,
	0x1e, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f,
	0x64, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f,
	0x64, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x13, 0x1a, 0x0e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x6f, 0x64, 0x6f,
	0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x3a, 0x01, 0x2a, 0x42, 0x4c, 0x0a, 0x1a, 0x64, 0x65, 0x76, 0x2e,
	0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x6c,
	0x69, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x42, 0x0f, 0x54, 0x6f, 0x64, 0x6f, 0x4c, 0x69, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x56, 0x31, 0x50, 0x01, 0x5a, 0x1b, 0x74, 0x6f, 0x64, 0x6f, 0x6c,
	0x69, 0x73, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74,
	0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_todolist_v1_todolist_proto_rawDescOnce sync.Once
	file_todolist_v1_todolist_proto_rawDescData = file_todolist_v1_todolist_proto_rawDesc
)

func file_todolist_v1_todolist_proto_rawDescGZIP() []byte {
	file_todolist_v1_todolist_proto_rawDescOnce.Do(func() {
		file_todolist_v1_todolist_proto_rawDescData = protoimpl.X.CompressGZIP(file_todolist_v1_todolist_proto_rawDescData)
	})
	return file_todolist_v1_todolist_proto_rawDescData
}

var file_todolist_v1_todolist_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_todolist_v1_todolist_proto_goTypes = []interface{}{
	(*ShowKeyTodoRequest)(nil), // 0: todolist.v1.ShowKeyTodoRequest
	(*ShowAllTodoRequest)(nil), // 1: todolist.v1.ShowAllTodoRequest
	(*DeleteTodoRequest)(nil),  // 2: todolist.v1.DeleteTodoRequest
	(*ModifyTodoRequest)(nil),  // 3: todolist.v1.ModifyTodoRequest
	(*AddTodoRequest)(nil),     // 4: todolist.v1.AddTodoRequest
	(*AddTodoReply)(nil),       // 5: todolist.v1.AddTodoReply
	(*DeleteTodoReply)(nil),    // 6: todolist.v1.DeleteTodoReply
	(*ModifyTodoReply)(nil),    // 7: todolist.v1.ModifyTodoReply
	(*ShowAllTodoReply)(nil),   // 8: todolist.v1.ShowAllTodoReply
	(*ShowKeyTodoReply)(nil),   // 9: todolist.v1.ShowKeyTodoReply
}
var file_todolist_v1_todolist_proto_depIdxs = []int32{
	4, // 0: todolist.v1.Todolist.Add:input_type -> todolist.v1.AddTodoRequest
	1, // 1: todolist.v1.Todolist.ShowAll:input_type -> todolist.v1.ShowAllTodoRequest
	0, // 2: todolist.v1.Todolist.ShowKey:input_type -> todolist.v1.ShowKeyTodoRequest
	2, // 3: todolist.v1.Todolist.Delete:input_type -> todolist.v1.DeleteTodoRequest
	3, // 4: todolist.v1.Todolist.Modify:input_type -> todolist.v1.ModifyTodoRequest
	5, // 5: todolist.v1.Todolist.Add:output_type -> todolist.v1.AddTodoReply
	8, // 6: todolist.v1.Todolist.ShowAll:output_type -> todolist.v1.ShowAllTodoReply
	9, // 7: todolist.v1.Todolist.ShowKey:output_type -> todolist.v1.ShowKeyTodoReply
	6, // 8: todolist.v1.Todolist.Delete:output_type -> todolist.v1.DeleteTodoReply
	7, // 9: todolist.v1.Todolist.Modify:output_type -> todolist.v1.ModifyTodoReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_todolist_v1_todolist_proto_init() }
func file_todolist_v1_todolist_proto_init() {
	if File_todolist_v1_todolist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_todolist_v1_todolist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowKeyTodoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todolist_v1_todolist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowAllTodoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todolist_v1_todolist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTodoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todolist_v1_todolist_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyTodoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todolist_v1_todolist_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTodoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todolist_v1_todolist_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTodoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todolist_v1_todolist_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTodoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todolist_v1_todolist_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyTodoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todolist_v1_todolist_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowAllTodoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todolist_v1_todolist_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowKeyTodoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_todolist_v1_todolist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todolist_v1_todolist_proto_goTypes,
		DependencyIndexes: file_todolist_v1_todolist_proto_depIdxs,
		MessageInfos:      file_todolist_v1_todolist_proto_msgTypes,
	}.Build()
	File_todolist_v1_todolist_proto = out.File
	file_todolist_v1_todolist_proto_rawDesc = nil
	file_todolist_v1_todolist_proto_goTypes = nil
	file_todolist_v1_todolist_proto_depIdxs = nil
}
